CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash VARCHAR(32) NOT NULL,
    token VARCHAR(64) NOT NULL,
    number VARCHAR(10) NULL,
    status INTEGER NOT NULL DEFAULT 1,
    description VARCHAR(1000) NULL,
    create_date TIMESTAMP NOT NULL,
    update_date TIMESTAMP NULL,

    user_id INTEGER NULL,

    customer_data_id INTEGER NOT NULL,
    delivery_data_id INTEGER NOT NULL,
    manager_id INTEGER NOT NULL,
    carrier_id INTEGER NOT NULL,

    tracking_number VARCHAR(50) NULL,
    delivery_price_euro NUMERIC(10,2) NULL,

    pay_type SMALLINT NOT NULL,

    cur_rate NUMERIC(10,2) NULL DEFAULT 1,
    currency VARCHAR(3) NOT NULL DEFAULT 'EUR',

    total_price NUMERIC(10,2) NULL,
    discount NUMERIC(10,2) NULL,
    vat_type INTEGER NOT NULL DEFAULT 0,
    vat_number VARCHAR(100) NULL,
    tax_number VARCHAR(50) NULL,

    /*
    should delete if you can calculate as discount==0
    */
    spec_price BOOLEAN NULL,

    address_payer INTEGER NULL,
    bank_details TEXT NULL,

    offset_date TIMESTAMP NULL,
    offset_reason SMALLINT NULL,
    proposed_date TIMESTAMP NULL,
    ship_date TIMESTAMP NULL,

    weight_gross NUMERIC(10,3) NULL,

    /*
    can replace them with few tables like order_props + order_props_value
    */
--     product_review BOOLEAN NULL,
--     mirror SMALLINT NULL,
--     entrance_review SMALLINT NULL,
--     show_msg BOOLEAN NULL,
--     bank_transfer_requested BOOLEAN NULL,
--     accept_pay BOOLEAN NULL,
);

CREATE TABLE IF NOT EXISTS order_props (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NULL,
    type VARCHAR(10) NULL,
    required BOOLEAN NULL
);

CREATE TABLE IF NOT EXISTS order_props_value (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    order_prop_id INTEGER NOT NULL,
    value VARCHAR(50) NULL
);



CREATE TABLE IF NOT EXISTS orders_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL,
  date_insert TIMESTAMP NOT NULL,
  status_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL
);


CREATE TABLE IF NOT EXISTS orders_status (
     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(50) NULL
/*
... some fields?
*/
);

CREATE TABLE IF NOT EXISTS carriers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NULL,
    contact_data VARCHAR(255) NULL,
    /*
    ... some fields?
    */
);

CREATE TABLE IF NOT EXISTS managers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NULL,
    email VARCHAR(30) NULL,
    phone VARCHAR(20) NULL
);

CREATE TABLE IF NOT EXISTS users_customer_data (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    email VARCHAR(100) NULL,
    sex SMALLINT NULL,
    client_name VARCHAR(255) NULL,
    client_surname VARCHAR(255) NULL,
    company_name VARCHAR(255) NULL,
    locale VARCHAR(5) NOT NULL
    /*
    ... some fields?
    */
);


CREATE TABLE IF NOT EXISTS users_delivery_data (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    delivery_id INTEGER NOT NULL,
    postal_index VARCHAR(20) NULL,
    country INTEGER NULL,
    region VARCHAR(50) NULL,
    city VARCHAR(200) NULL,
    address VARCHAR(300) NULL,
    building VARCHAR(200) NULL,
    phone_code VARCHAR(20) NULL,
    phone VARCHAR(20) NULL,
    calculate_type SMALLINT NULL DEFAULT 0,
    apartment_office VARCHAR(30) NULL,
    warehouse_data TEXT NULL,
    address_equal BOOLEAN NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    /*
    ... some fields
    */
);

CREATE TABLE IF NOT EXISTS orders_article (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

--     or for basket you have other table?
    order_id INTEGER NULL,

    article_id INTEGER NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    price_eur NUMERIC(10,2) NULL,
    currency VARCHAR(3) NULL,
    measure VARCHAR(2) NULL,
    weight NUMERIC(10,3) NOT NULL,
    multiple_pallet SMALLINT NULL,
    packaging_count NUMERIC(10,2) NOT NULL,
    pallet NUMERIC(10,2) NOT NULL,
    swimming_pool BOOLEAN NOT NULL DEFAULT FALSE,

    /*
     should leave if you can deliver items separately
     */
--     delivery_time_min DATE NULL,
--     delivery_time_max DATE NULL,

);

CREATE UNIQUE INDEX IF NOT EXISTS uq_orders_hash ON orders (hash);
CREATE UNIQUE INDEX IF NOT EXISTS uq_orders_token ON orders (token);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_customer_data_id ON orders (customer_data_id);
CREATE INDEX IF NOT EXISTS idx_orders_delivery_data_id ON orders (delivery_data_id);
CREATE INDEX IF NOT EXISTS idx_orders_manager_id ON orders (manager_id);
CREATE INDEX IF NOT EXISTS idx_orders_carrier_id ON orders (carrier_id);
CREATE INDEX IF NOT EXISTS idx_orders_address_payer ON orders (address_payer);
CREATE INDEX IF NOT EXISTS idx_orders_create_date ON orders (create_date);
CREATE INDEX IF NOT EXISTS idx_orders_create_date_status ON orders (create_date, status);

CREATE INDEX IF NOT EXISTS idx_order_props_name ON order_props (name);

CREATE INDEX IF NOT EXISTS idx_order_props_value_order_id ON order_props_value (order_id);
CREATE INDEX IF NOT EXISTS idx_order_props_value_order_prop_id ON order_props_value (order_prop_id);

CREATE INDEX IF NOT EXISTS idx_orders_history_order_id ON orders_history (order_id);
CREATE INDEX IF NOT EXISTS idx_orders_history_status_id ON orders_history (status_id);
CREATE INDEX IF NOT EXISTS idx_orders_history_user_id ON orders_history (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_history_date_insert ON orders_history (date_insert);

CREATE INDEX IF NOT EXISTS idx_users_customer_data_user_id ON users_customer_data (user_id);
CREATE INDEX IF NOT EXISTS idx_users_delivery_data_user_id ON users_delivery_data (user_id);

CREATE INDEX IF NOT EXISTS idx_orders_article_article_id ON orders_article (article_id);
CREATE INDEX IF NOT EXISTS idx_orders_article_order_id ON orders_article (order_id);
