<?php

declare(strict_types=1);

namespace App\Command;

use App\Entity\Order;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(name: 'app:seed:orders', description: 'Seed test orders into PostgreSQL')]
final class SeedOrdersCommand extends Command
{
    public function __construct(private readonly EntityManagerInterface $em)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('count', null, InputOption::VALUE_REQUIRED, 'How many test orders to generate', '50')
            ->addOption('append', null, InputOption::VALUE_NONE, 'Append test data even if orders already exist');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $count = max(1, (int) $input->getOption('count'));
        $append = (bool) $input->getOption('append');

        $existing = (int) $this->em->getConnection()->fetchOne('SELECT COUNT(*) FROM orders');
        if ($existing > 0 && !$append) {
            $io->note(sprintf('orders already contains %d rows. Use --append to add more.', $existing));

            return Command::SUCCESS;
        }

        $now = new \DateTimeImmutable('now');
        for ($i = 1; $i <= $count; ++$i) {
            $daysAgo = random_int(0, 365);
            $createdAt = $now
                ->sub(new \DateInterval(sprintf('P%dD', $daysAgo)))
                ->setTime(random_int(0, 23), random_int(0, 59), random_int(0, 59));

            $order = new Order(
                hash: md5(uniqid((string) $i, true)),
                token: hash('sha256', uniqid((string) random_int(1, PHP_INT_MAX), true)),
                payType: random_int(1, 3),
                name: sprintf('Test order #%d', $existing + $i),
                createDate: $createdAt,
            );

            $order->setStatus(random_int(1, 5));
            $order->setEmail(sprintf('test+%d@example.com', $existing + $i));
            $order->setDescription('Generated by app:seed:orders command.');
            $order->setDeliveryPriceEuro(random_int(1000, 30000) / 100);

            $this->em->persist($order);
        }

        $this->em->flush();

        $total = (int) $this->em->getConnection()->fetchOne('SELECT COUNT(*) FROM orders');
        $io->success(sprintf('Inserted %d test orders. Total rows in orders: %d', $count, $total));

        return Command::SUCCESS;
    }
}
